version: '3'

services:
  dash-pipeline:
    build: .
    image: matefarkas/dash-pipeline
    environment:
      JKS_STORE_BASE64:
      JKS_STORE_PASSWORD:
      JKS_KEY_ALIAS:
      JKS_KEY_PASSWORD:
      RELEASE:
      SUPPLY_JSON_KEY_DATA:
    volumes:
      - .:/build/:rw
