version: '3'

services:
  dash-pipeline:
    build: .
    image: matefarkas/dash-pipeline
    environment:
      JKS_STORE_BASE64:     ${JKS_STORE_BASE64}
      JKS_STORE_PASSWORD:   ${JKS_STORE_PASSWORD}
      JKS_KEY_ALIAS:        ${JKS_KEY_ALIAS}
      JKS_KEY_PASSWORD:     ${JKS_KEY_PASSWORD}
      SUPPLY_JSON_KEY_DATA: ${SUPPLY_JSON_KEY_DATA}
    volumes:
      - .:/build/:rw
