# vim: set syntax=ruby:

require 'base64'

opt_out_usage
skip_docs

default_platform(:android)

platform :android do
  desc 'Runs all the tests'
  lane :test do
    gradle(task: 'test')
  end

  desc 'Submit a new Beta Build to Google Play'
  lane :beta do
    Tempfile.create('jks') do |jks|
      jks.write(Base64.decode64(ENV['JKS_STORE_BASE64']))
      jks.rewind

      gradle(
        task: 'bundle',
        build_type: 'Release',
        print_command: false,
        properties: {
          'android.injected.signing.store.file'     => jks.path,
          'android.injected.signing.store.password' => ENV['JKS_STORE_PASSWORD'],
          'android.injected.signing.key.alias'      => ENV['JKS_KEY_ALIAS'],
          'android.injected.signing.key.password'   => ENV['JKS_KEY_PASSWORD'],
        },
      )
    end

    gradle(task: 'generateChangelogs')

    upload_to_play_store(
      track: 'beta',
      validate_only: ENV['RELEASE'] == 'true' ? false : true,
    )
  end
end
