title: DASH
description: >-
  Dashboard for Android and Wear OS
  - Track bits of information on your phone and watch

theme: jekyll-theme-hacker

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - docker-compose.yaml
  - package.json
